apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auto-scaler
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: auto-scaler
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
